In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [9]:
import pandas as pd
dataset = pd.read_csv('/content/drive/My Drive/final_data.csv')

In [10]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 46802):
  review = re.sub('[^a-zA-Z]', ' ', dataset['title'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [11]:
print(corpus)

['u budget fight loom republican flip fiscal script', 'u militari accept transgend recruit monday pentagon', 'senior u republican senat let mr mueller job', 'fbi russia probe help australian diplomat tip nyt', 'trump want postal servic charg much amazon shipment', 'white hous congress prepar talk spend immigr', 'trump say russia probe fair timelin unclear nyt', 'factbox trump twitter dec approv rate amazon', 'trump twitter dec global warm', 'alabama offici certifi senat elect jone today despit challeng cnn', 'jone certifi u senat winner despit moor challeng', 'new york governor question constitution feder tax overhaul', 'factbox trump twitter dec vaniti fair hillari clinton', 'trump twitter dec trump iraq syria', 'man say deliv manur mnuchin protest new u tax law', 'virginia offici postpon lotteri draw decid tie statehous elect', 'u lawmak question businessman trump tower meet sourc', 'trump twitter dec hillari clinton tax cut bill', 'u appeal court reject challeng trump voter fraud pa

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 2000)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [48]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [49]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [1 1]]


In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[4193  331]
 [ 830 4007]]


0.8759747890182673

In [27]:
#Trying another model

In [51]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB() 
clf.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [52]:
y_pred1 = classifier.predict(X_test)
print(np.concatenate((y_pred1.reshape(len(y_pred1),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [1 1]]


In [53]:
cm_multinomialNB= confusion_matrix(y_test, y_pred)
print(cm_multinomialNB)
accuracy_score(y_test, y_pred1)

[[4193  331]
 [ 830 4007]]


0.8759747890182673

In [31]:
#Trying yet another model

In [54]:
from sklearn.linear_model import PassiveAggressiveClassifier
linear_clf = PassiveAggressiveClassifier()
linear_clf.fit(X_train, y_train)

PassiveAggressiveClassifier(C=1.0, average=False, class_weight=None,
                            early_stopping=False, fit_intercept=True,
                            loss='hinge', max_iter=1000, n_iter_no_change=5,
                            n_jobs=None, random_state=None, shuffle=True,
                            tol=0.001, validation_fraction=0.1, verbose=0,
                            warm_start=False)

In [55]:
y_pred2 = classifier.predict(X_test)
print(np.concatenate((y_pred1.reshape(len(y_pred2),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [0 0]
 [1 1]
 [1 1]]


In [56]:
cm_classifier= confusion_matrix(y_test, y_pred)
print(cm_classifier)
accuracy_score(y_test, y_pred2)

[[4193  331]
 [ 830 4007]]


0.8759747890182673